apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tra-documents-service-api
spec:
  selector:
    matchLabels:
      app: app-tra-documents-service-api
  template:
    metadata:
      labels:
        app: app-tra-documents-service-api
    spec:
      containers:
      - name: app-tra-documents-service-api
        image: oiestradag/app-tra-documents-service-api
        env:
        - name: PORT
          value: "80"
        - name: APP_VERSION
          value: "develop"
        - name: SQL_URL_CONECTION
          value: "jdbc:h2:mem:testdb"
        - name: SQL_USERNAME
          value: "develop"
        - name: SQL_PASSWORD
          value: "develop"	 
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: app-tra-documents-service-api
spec:
  type: NodePort
  selector:
    app: app-tra-documents-service-api
  ports:
  - port: 8081
    targetPort: 80
